/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Obs.ControlRoom;
import java.awt.Color;

/**
 *
 * @author hiranyamendis
 */
public class Submarine extends javax.swing.JFrame implements Obs.Observer {

    private ControlRoom controlRoom;
    
    public Submarine(ControlRoom controlRoom) {
        this.controlRoom=controlRoom;
        initComponents();
        setVisible(true);
        btnShoot.setEnabled(false);
        btnSonarOperation.setEnabled(false);
        btnToahawkMissile.setEnabled(false);
        btnTridentMissile.setEnabled(false);
        spnSoilders.setValue(100);
        spnAmmo.setValue(100);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnTridentMissile = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblAreaClear = new javax.swing.JLabel();
        btnShoot = new javax.swing.JButton();
        btnToahawkMissile = new javax.swing.JButton();
        btnSonarOperation = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMsgBox = new javax.swing.JTextArea();
        txtSendMsg = new javax.swing.JTextField();
        btnSend = new javax.swing.JButton();
        chkPosition = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        spnSoilders = new javax.swing.JSpinner();
        spnAmmo = new javax.swing.JSpinner();
        txtEnergyAmount = new javax.swing.JTextField();
        sldEnergyAmount = new javax.swing.JSlider();
        sldOxygenAmount = new javax.swing.JSlider();
        txtOxygenAmount = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnTridentMissile.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnTridentMissile.setText("Trident-2 Missile");
        btnTridentMissile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTridentMissileActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Submarine.png"))); // NOI18N

        lblAreaClear.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblAreaClear.setText("Area Is Not Cleared");

        btnShoot.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnShoot.setText("Shoot");
        btnShoot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShootActionPerformed(evt);
            }
        });

        btnToahawkMissile.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnToahawkMissile.setText("Toahawk Missile");
        btnToahawkMissile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToahawkMissileActionPerformed(evt);
            }
        });

        btnSonarOperation.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnSonarOperation.setText("Sonar Operation");
        btnSonarOperation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSonarOperationActionPerformed(evt);
            }
        });

        txtMsgBox.setColumns(20);
        txtMsgBox.setRows(5);
        jScrollPane1.setViewportView(txtMsgBox);

        btnSend.setFont(new java.awt.Font("Helvetica Neue", 1, 16)); // NOI18N
        btnSend.setText("Send");
        btnSend.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        btnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendActionPerformed(evt);
            }
        });

        chkPosition.setBackground(new java.awt.Color(255, 255, 255));
        chkPosition.setFont(new java.awt.Font("Helvetica Neue", 1, 16)); // NOI18N
        chkPosition.setText(" Position");
        chkPosition.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        chkPosition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkPositionActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel4.setText("Ammo");

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel3.setText("Soilders");

        spnSoilders.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spnSoildersStateChanged(evt);
            }
        });

        spnAmmo.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spnAmmoStateChanged(evt);
            }
        });

        txtEnergyAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEnergyAmountActionPerformed(evt);
            }
        });

        sldEnergyAmount.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        sldEnergyAmount.setMajorTickSpacing(20);
        sldEnergyAmount.setMinorTickSpacing(10);
        sldEnergyAmount.setOrientation(javax.swing.JSlider.VERTICAL);
        sldEnergyAmount.setPaintLabels(true);
        sldEnergyAmount.setPaintTicks(true);
        sldEnergyAmount.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sldEnergyAmountStateChanged(evt);
            }
        });

        sldOxygenAmount.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        sldOxygenAmount.setMajorTickSpacing(20);
        sldOxygenAmount.setMinorTickSpacing(10);
        sldOxygenAmount.setOrientation(javax.swing.JSlider.VERTICAL);
        sldOxygenAmount.setPaintLabels(true);
        sldOxygenAmount.setPaintTicks(true);
        sldOxygenAmount.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sldOxygenAmountStateChanged(evt);
            }
        });

        txtOxygenAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOxygenAmountActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 15)); // NOI18N
        jLabel2.setText("Oxygen");

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 1, 15)); // NOI18N
        jLabel5.setText("Energy");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnShoot, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnSonarOperation, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblAreaClear)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnToahawkMissile, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnTridentMissile, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkPosition, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(17, 17, 17)
                                        .addComponent(spnAmmo, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(spnSoilders, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtSendMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSend, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtEnergyAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(sldEnergyAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtOxygenAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(sldOxygenAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(43, 43, 43)
                .addComponent(jLabel2)
                .addGap(38, 38, 38))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(spnSoilders, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(spnAmmo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSonarOperation, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnShoot, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(chkPosition))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnToahawkMissile, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTridentMissile, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSendMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSend, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                        .addComponent(lblAreaClear, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(347, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtEnergyAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sldEnergyAmount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtOxygenAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sldOxygenAmount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(12, 12, 12))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTridentMissileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTridentMissileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTridentMissileActionPerformed

    private void btnShootActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShootActionPerformed
        int count = Integer.parseInt(spnSoilders.getValue().toString());
        spnSoilders.setValue(count-1);
        int value = Integer.parseInt(spnAmmo.getValue().toString());
        spnAmmo.setValue(count-1);
    }//GEN-LAST:event_btnShootActionPerformed

    private void btnToahawkMissileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToahawkMissileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnToahawkMissileActionPerformed

    private void btnSonarOperationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSonarOperationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSonarOperationActionPerformed

    private void btnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendActionPerformed
        controlRoom.sendPrivateMsg("Submarine : "+txtSendMsg.getText());
    }//GEN-LAST:event_btnSendActionPerformed

    private void chkPositionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkPositionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkPositionActionPerformed

    private void txtEnergyAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEnergyAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEnergyAmountActionPerformed

    private void txtOxygenAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOxygenAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOxygenAmountActionPerformed

    private void spnSoildersStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spnSoildersStateChanged
        
    }//GEN-LAST:event_spnSoildersStateChanged

    private void spnAmmoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spnAmmoStateChanged
        
    }//GEN-LAST:event_spnAmmoStateChanged

    private void sldEnergyAmountStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldEnergyAmountStateChanged
        txtEnergyAmount.setText(sldEnergyAmount.getValue()+"");
    }//GEN-LAST:event_sldEnergyAmountStateChanged

    private void sldOxygenAmountStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldOxygenAmountStateChanged
        txtOxygenAmount.setText(sldOxygenAmount.getValue()+"");
    }//GEN-LAST:event_sldOxygenAmountStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSend;
    private javax.swing.JButton btnShoot;
    private javax.swing.JButton btnSonarOperation;
    private javax.swing.JButton btnToahawkMissile;
    private javax.swing.JButton btnTridentMissile;
    private javax.swing.JCheckBox chkPosition;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAreaClear;
    private javax.swing.JSlider sldEnergyAmount;
    private javax.swing.JSlider sldOxygenAmount;
    private javax.swing.JSpinner spnAmmo;
    private javax.swing.JSpinner spnSoilders;
    private javax.swing.JTextField txtEnergyAmount;
    private javax.swing.JTextArea txtMsgBox;
    private javax.swing.JTextField txtOxygenAmount;
    private javax.swing.JTextField txtSendMsg;
    // End of variables declaration//GEN-END:variables

    @Override
    public void areaCleared(boolean areaClear) {
        if (areaClear) {
            lblAreaClear.setOpaque(true);
            lblAreaClear.setText("Area Is Cleared");
            lblAreaClear.setBackground(Color.GREEN);
        } else {
            lblAreaClear.setOpaque(true);
            lblAreaClear.setText("Area Is Not Cleared");
            lblAreaClear.setBackground(Color.RED);
        }
    }

    @Override
    public void txtSender(String msg) {
        txtMsgBox.setText("Main Controller : " + msg);
    }

    @Override
    public void defenceUnloker(int value) {
        if (chkPosition.isSelected()) {
            if (value >= 20) {
                btnShoot.setEnabled(true);
            } else {
                btnShoot.setEnabled(false);
            }
            if (value >= 40) {
                btnSonarOperation.setEnabled(true);
            } else {
                btnSonarOperation.setEnabled(false);
            }
            if (value >= 60) {
                btnToahawkMissile.setEnabled(true);
            } else {
                btnToahawkMissile.setEnabled(false);
            }
            if (value >= 80) {
                btnTridentMissile.setEnabled(true);
            } else {
                btnTridentMissile.setEnabled(false);
            }
        } else{
            btnShoot.setEnabled(false);
            btnSonarOperation.setEnabled(false);
            btnToahawkMissile.setEnabled(false);
            btnTridentMissile.setEnabled(false);
        }
    }

    @Override
    public void getPrivateMsg(String msg) {
        
    }

}
