/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Obs.ControlRoom;
import java.awt.Color;
import javax.swing.Timer;

/**
 *
 * @author hiranyamendis
 */
public class Tank extends javax.swing.JFrame implements Obs.Observer {

    private ControlRoom controlRoom;
    private Timer timer;
    private boolean timerStarted = false;
    
    public Tank(ControlRoom controlRoom) {
        this.controlRoom=controlRoom;
        initComponents();
        setVisible(true);
        btnShoot.setEnabled(false);
        btnMissileOperation.setEnabled(false);
        btnRadarOperation.setEnabled(false);
        btnRotateShooting.setEnabled(false);
        spnSoilders.setValue(100);
        spnAmmo.setValue(100);
        txtFuelAmount.setText(sldFuelAmount.getValue() + "");
        fuelStatus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        spnSoilders = new javax.swing.JSpinner();
        spnAmmo = new javax.swing.JSpinner();
        chkPosition = new javax.swing.JCheckBox();
        btnShoot = new javax.swing.JButton();
        btnMissileOperation = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMsgBox = new javax.swing.JTextArea();
        lblAreaClear = new javax.swing.JLabel();
        txtSendMsg = new javax.swing.JTextField();
        btnRadarOperation = new javax.swing.JButton();
        txtFuelAmount = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        sldFuelAmount = new javax.swing.JSlider();
        jLabel4 = new javax.swing.JLabel();
        btnSend = new javax.swing.JButton();
        btnRotateShooting = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Helicopter.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        chkPosition.setBackground(new java.awt.Color(255, 255, 255));
        chkPosition.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        chkPosition.setText(" Position");
        chkPosition.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        chkPosition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkPositionActionPerformed(evt);
            }
        });

        btnShoot.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        btnShoot.setText("Shoot");
        btnShoot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShootActionPerformed(evt);
            }
        });

        btnMissileOperation.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        btnMissileOperation.setText("Missile Operation");
        btnMissileOperation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMissileOperationActionPerformed(evt);
            }
        });

        txtMsgBox.setColumns(20);
        txtMsgBox.setRows(5);
        jScrollPane1.setViewportView(txtMsgBox);

        lblAreaClear.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblAreaClear.setText("Area Is Not Cleared");

        txtSendMsg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSendMsgActionPerformed(evt);
            }
        });

        btnRadarOperation.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        btnRadarOperation.setText("Radar Operation");
        btnRadarOperation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRadarOperationActionPerformed(evt);
            }
        });

        txtFuelAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFuelAmountActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel3.setText("Soilders");

        sldFuelAmount.setFont(new java.awt.Font("Helvetica Neue", 1, 12)); // NOI18N
        sldFuelAmount.setMajorTickSpacing(20);
        sldFuelAmount.setMinorTickSpacing(10);
        sldFuelAmount.setOrientation(javax.swing.JSlider.VERTICAL);
        sldFuelAmount.setPaintLabels(true);
        sldFuelAmount.setPaintTicks(true);
        sldFuelAmount.setValue(100);
        sldFuelAmount.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sldFuelAmountStateChanged(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel4.setText("Ammo");

        btnSend.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnSend.setText("Send");
        btnSend.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        btnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendActionPerformed(evt);
            }
        });

        btnRotateShooting.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        btnRotateShooting.setText("Rotate Shooting");
        btnRotateShooting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRotateShootingActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Tank.png"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel5.setText("Fuel Amount");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtSendMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnSend, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAreaClear)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btnRadarOperation, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                                    .addComponent(btnShoot, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnMissileOperation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnRotateShooting, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(spnSoilders, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(spnAmmo, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(chkPosition, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)))
                        .addGap(43, 43, 43)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(sldFuelAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtFuelAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(lblAreaClear, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(btnMissileOperation, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnShoot, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(btnRadarOperation, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnRotateShooting, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel3)
                                            .addComponent(spnSoilders, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel4)
                                            .addComponent(spnAmmo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(21, 21, 21)
                                        .addComponent(chkPosition)))
                                .addGap(24, 24, 24)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtSendMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnSend, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtFuelAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(sldFuelAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chkPositionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkPositionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkPositionActionPerformed

    private void btnShootActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShootActionPerformed
        int count = Integer.parseInt(spnSoilders.getValue().toString());
        spnSoilders.setValue(count-1);
        int value = Integer.parseInt(spnAmmo.getValue().toString());
        spnAmmo.setValue(count-1);
    }//GEN-LAST:event_btnShootActionPerformed

    private void btnMissileOperationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMissileOperationActionPerformed

    }//GEN-LAST:event_btnMissileOperationActionPerformed

    private void txtSendMsgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSendMsgActionPerformed

    }//GEN-LAST:event_txtSendMsgActionPerformed

    private void btnRadarOperationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRadarOperationActionPerformed

    }//GEN-LAST:event_btnRadarOperationActionPerformed

    private void txtFuelAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFuelAmountActionPerformed

    }//GEN-LAST:event_txtFuelAmountActionPerformed

    private void sldFuelAmountStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldFuelAmountStateChanged
        txtFuelAmount.setText(sldFuelAmount.getValue()+"");
    }//GEN-LAST:event_sldFuelAmountStateChanged

    private void btnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendActionPerformed
        controlRoom.sendMsg("Tank : "+txtSendMsg.getText());
        txtSendMsg.setText("");
    }//GEN-LAST:event_btnSendActionPerformed

    private void btnRotateShootingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRotateShootingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRotateShootingActionPerformed

    private void fuelStatus(){
        if (!timerStarted) {
            timer = new javax.swing.Timer(4000, new java.awt.event.ActionListener() {
                @Override
                public void actionPerformed(java.awt.event.ActionEvent e) {
                    int value = sldFuelAmount.getValue();
                    if (value > 0) {
                        sldFuelAmount.setValue(value - 1);
                        txtFuelAmount.setText(sldFuelAmount.getValue() + "");
                    } else {
                        timer.stop();
                    }
                }
            });
            timer.start();
            timerStarted = true;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMissileOperation;
    private javax.swing.JButton btnRadarOperation;
    private javax.swing.JButton btnRotateShooting;
    private javax.swing.JButton btnSend;
    private javax.swing.JButton btnShoot;
    private javax.swing.JCheckBox chkPosition;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAreaClear;
    private javax.swing.JSlider sldFuelAmount;
    private javax.swing.JSpinner spnAmmo;
    private javax.swing.JSpinner spnSoilders;
    private javax.swing.JTextField txtFuelAmount;
    private javax.swing.JTextArea txtMsgBox;
    private javax.swing.JTextField txtSendMsg;
    // End of variables declaration//GEN-END:variables

    @Override
    public void areaCleared(boolean areaClear) {
        if (areaClear) {
            lblAreaClear.setOpaque(true);
            lblAreaClear.setText("Area Is Cleared");
            lblAreaClear.setBackground(Color.GREEN);
        } else {
            lblAreaClear.setOpaque(true);
            lblAreaClear.setText("Area Is Not Cleared");
            lblAreaClear.setBackground(Color.RED);
        }
    }

    @Override
    public void txtSender(String msg) {
        txtMsgBox.append("Main Controller : " + msg+"\n");
    }

    @Override
    public void defenceUnloker(int value) {
        if (chkPosition.isSelected()) {
            if (value >= 20) {
                btnShoot.setEnabled(true);
            } else {
                btnShoot.setEnabled(false);
            }
            if (value >= 40) {
                btnMissileOperation.setEnabled(true);
            } else {
                btnMissileOperation.setEnabled(false);
            }
            if (value >= 60) {
                btnRadarOperation.setEnabled(true);
            } else {
                btnRadarOperation.setEnabled(false);
            }
            if (value >= 80) {
                btnRotateShooting.setEnabled(true);
            } else {
                btnRotateShooting.setEnabled(false);
            }
        }else{
            btnShoot.setEnabled(false);
            btnMissileOperation.setEnabled(false);
            btnRadarOperation.setEnabled(false);
            btnRotateShooting.setEnabled(false);
        }
    }

    @Override
    public void getMsg(String msg) {
        
    }

    @Override
    public void getPrivateMsg(String defence, String msg) {
        if(defence=="Tank"){
            txtMsgBox.append(msg+"\n");
        }
    }


}
